version: '3.8'

services:
  orchestrator:
    build: .
    ports:
      - "8080:8000"
    environment:
      # Настройки классификатора
      - CLASSIFIER_URL=http://classifier:8000/api/v1/tender/classify-tender
      - CLASSIFIER_API_KEY=${CLASSIFIER_API_KEY}

      # Настройки стандартизатора
      - STANDARDIZER_URL=http://standardizer:8000/api/v1/standardize
      - STANDARDIZER_API_KEY=${STANDARDIZER_API_KEY}

      # Настройки сервиса подбора товаров
      - MATCHER_URL=http://matcher:8000/api/v1/match
      - MATCHER_API_KEY=${MATCHER_API_KEY}

      # Настройки оркестратора
      - REQUIRE_API_KEY=${REQUIRE_API_KEY:-false}
      - ORCHESTRATOR_API_KEY=${ORCHESTRATOR_API_KEY}

      # Общие настройки
      - REQUEST_TIMEOUT=300
      - LOG_LEVEL=${LOG_LEVEL:-INFO}

    networks:
      - tender-network

    restart: unless-stopped

networks:
  tender-network:
    external: true