services:
  orchestrator:
    build: .
    env_file:
      - .env
    container_name: tender-orchestrator
    ports:
      - "8080:8000"
    environment:
      # URLs сервисов
      - CLASSIFIER_URL=http://okpd2_classifier:8000/api/v1/tender/classify-tender
      - STANDARDIZER_URL=http://standardizer-service:8000/api/v1/standardization/tender/standardize
      - MATCHER_URL=http://tender_positions_match_service:8000/api/v1/tenders/match



      # API ключи сервисов
      - CLASSIFIER_API_KEY=${CLASSIFIER_API_KEY}
      - STANDARDIZER_API_KEY=${STANDARDIZER_API_KEY}
      - MATCHER_API_KEY=${MATCHER_API_KEY}

      # Настройки оркестратора
      - REQUIRE_API_KEY=${REQUIRE_API_KEY:-false}
      - ORCHESTRATOR_API_KEY=${ORCHESTRATOR_API_KEY}

      # Общие настройки
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-300}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}

    networks:
      - tender-services

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  tender-services:
    external: true